### ISSUE TITLE
Error with emoji-mart on Next.js

### ISSUE THREAD

**Issue by vicesalles** [3box/3box-profile-edit-react#11]
I'm building a nextjs site and i'd like to provide auth by 3box. I love the idea of the plugin but i'm getting an error:

`./node_modules/3box-profile-edit-react/node_modules/emoji-mart/css/emoji-mart.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .emoji-mart,
| .emoji-mart * {
|   box-sizing: border-box;`

**Comment by oznekenzo** [comment]
@vicesalles you need to set up your app to accept either css or scss in your webpack configs, this really isnt an issue with the component

**Comment by jadbox** [comment]
@oznekenzo Adding scss/css to nextjs does not resolve this issue as nextjs does not build css modules that are stored in node_modules. https://github.com/vercel/next.js/issues/10059

**Comment by jadbox** [comment]
@oznekenzo can we reopen?
