### ISSUE TITLE
Polished implementation from feedback / testing

### ISSUE THREAD

**Issue by michaelsena** [3box/3box-profile-edit-react#5]

**Comment by oznekenzo** [comment]
- [x] not closing on click away emoji mart
- [x] move a shortened address to the bottom next to save profile
- [x] “to all apps that use your 3box profile” no using, 
- [x] in hover, say apps not dapps, and remove general profile
- [x] in space warning, use app profile, not space profile
- [x] “Data here is saved to your application profiel”
- [x] Change data to “These fields” for app and 3box profile
- [x] 3box profile in default
- [x] is switch profile text bigger than field text?
- [x] only switch profile when you set it as the default
- [x] make settings dropdown bigger and move to where switch profile button is
- [x] see options, dont hide them
- [x] additional fields not in caps lock, make name, description and emoji non caps, keep 3box profile in caps
- [x] copy to clipboard
- [x] add dropdown and textarea
- [ ] hasChanged?
